### ISSUE TITLE
Have you considered

### ISSUE THREAD

**Issue by WhyNotHugo** [patrickbucher/docs#3]
Hey! I've been looking at your arch setup scripts, and found them quite interesting and am going to reuse some of this knowledge.

I wanted to share how I deal with setting up new personal devices, dunno if you've considered the approach, but it might be useful. What I do when setting up a new device is:

- Create a `/boot` partition, and set up LVM with a `/` partition, and a `swap` partition.
- I then `rsync` the filesystem from my previous computer to these new partitions.
- I `arch-chroot` the newly-rsync'd system, and re-run the EFI / bootloader setup.
- I change the params in `/boot/loader/entries/arch.conf` to the new partition UUIDs.

Once that's done, I can reboot and have my new device running as my old one. It's essentially a logical disk-swapping, but handles very well when disks change sizes.

You might be able to skip some setups steps with this. Cheers!

**Comment by patrickbucher** [comment]
Thanks for pointing this out (sorry, I only just noticed the issue). I think this makes a lot of sense when replacing a system. However, I usually want to start from a blank slate. But I  hope the setup script is useful for your adaptations!
