### ISSUE TITLE
HSLU-VPN

### ISSUE THREAD

**Issue by atreyasha** [patrickbucher/docs#4]
Hi Patrick,

Thank you for this documentation! I am currently working in HSLU and was trying to follow these [instructions](https://github.com/patrickbucher/docs/blob/master/div/hslu-vpn.md) to set up the HSLU-wide VPN. Unfortunately, I think they updated the software with different directory structures and executable names; that too with MFA.

Would you happen to have an updated version of instructions that work/worked for you?

**Comment by patrickbucher** [comment]
@atreyasha Sorry for ignoring your issue, I just stumbled upon it...
Sorry, I'm no longer at HSLU, so I have no access to test.
